theme: jekyll-theme-modernist
name: Hung Nguyen <br>(Nguyễn Đình Hưng)
permalink: /:year/:month/:day/:title/
paginate: 10
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
